<?php
    const MYSQL_USER = "REPLACE_MYSQL_USER";
    const MYSQL_PASSWORD = "REPLACE_MYSQL_PASSWORD";
    const MYSQL_DATABASE = "REPLACE_MYSQL_DATABASE";
    const GLOBAL_PASSWORD = "REPLACE_GLOBAL_PASSWORD";
    const HOST_NETWORK_ADDRESS = "REPLACE_HOST_NETWORK_ADDRESS";
?>
